sudo: required
services:
    - docker

before_install:
    - docker build -t mstefani77/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true mstefani77/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-1-330099215794"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"